### ISSUE TITLE
Support all custom validation for AsyncAPI 2.x.x

### ISSUE THREAD

**Issue by magicmatatjahu** [stoplightio/spectral#2100]
**Chore summary**

This issue contains list of rules that we need introduce in the AsyncAPI ruleset to fullfil all custom validation for 2.x.x versions.

> Note: This is a collective task, which serves for cooperation and informing the community what was done and what is left to do.

> Note: You can also write your own proposals/features/PRs in the comments, I will update then the main list.

**Tasks**

- [x] https://github.com/stoplightio/spectral/issues/1102
  - https://github.com/stoplightio/spectral/pull/2101
- [ ] https://github.com/stoplightio/spectral/issues/1103
- [x] https://github.com/stoplightio/spectral/issues/1732
- [x] https://github.com/stoplightio/spectral/issues/2102
  - https://github.com/stoplightio/spectral/pull/2121
- [x] https://github.com/stoplightio/spectral/issues/2103
  - https://github.com/stoplightio/spectral/pull/2104
- [x] https://github.com/stoplightio/spectral/issues/2123
  - https://github.com/stoplightio/spectral/pull/2122
- [x] https://github.com/stoplightio/spectral/issues/2124
  - https://github.com/stoplightio/spectral/pull/2122
- [x] https://github.com/stoplightio/spectral/issues/2223
  - https://github.com/stoplightio/spectral/pull/2224
- [ ] https://github.com/stoplightio/spectral/issues/2261
  - https://github.com/stoplightio/spectral/pull/2262
- https://github.com/stoplightio/spectral/pull/2281
- https://github.com/stoplightio/spectral/pull/2282
- https://github.com/stoplightio/spectral/pull/2284
- ...

**Additional context**

As the AsyncAPI team will take an active part in the development of the official ruleset for AsyncAPI we should support the validation of the overall specification.

**Comment by derberg** [comment]
we had a release where uniqueness of `messageId` was introduced
