### ISSUE TITLE
Update docs on how to use 4.X programatically 

### ISSUE THREAD

**Issue by cbetta** [stoplightio/spectral#365]
**Chore summary**

The current documentation on how to use Spectral programmatically does not reflect Spectral 4.

https://github.com/stoplightio/spectral/blob/develop/docs/js-api.md

**Tasks**
- [ ] Document how to load OAS rules 
- [ ] Document how to load custom rules 
- [ ] Document how to remove some of the default OAS rules

**Comment by philsturgeon** [comment]
Ah, well, it does. It shows you how to use spectral and add rules and functions directly without going via  the YAML rulesets. This approach is going away in the future and it’ll be all rulesets all the time, but we’ve not got that done. 

I’ll close this story and make a new one for tracking that work.

**Comment by cbetta** [comment]
@philsturgeon I think that doc only reflects 3.X though. I had to import from `require('@stoplight/spectral/rulesets/oas3')` to make that page work for me.

**Comment by philsturgeon** [comment]
Is that different to the line:

  const { oas3Functions, rules: oas3Rules } = require('@stoplight/spectral/rulesets/oas3');
Could you maybe send a PR with the changes you discovered? 

--
Phil Sturgeon
@philsturgeon

**Comment by cbetta** [comment]
```diff
+ require('@stoplight/spectral/dist/rulesets/oas3')
- require('@stoplight/spectral/rulesets/oas3')
```

**Comment by cbetta** [comment]
I’ve refrained from making a PR cause honestly I’m not even sure I’m doing this right.
