### ISSUE TITLE
Document OpenAPI v2/v3 Rules

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/spectral#395]
**Chore summary**

We need documentation for the OpenAPI rules we already have. If this is done after #311 it could be automated to use the "schema" defined, so we could make build a little script which loops through the functions and spits out a markdown table to go in the docs?

**Tasks**

- [ ] docs/rules.md
- [ ] docs/rules/oas.md
- [ ] docs/rules/oas2.md
- [ ] docs/rules/oas3.md
