### ISSUE TITLE
Make recommended: true by default and fix inheritence

### ISSUE THREAD

**Issue by miller79** [stoplightio/spectral#447]
_*Updated 2019-10-29:* Replaced with content from @marbemac's comment, which will be used to drive this issue._

recommended should be the default across the board - cli and ruleset extension. 

E.g. this:

```yaml
extends: spectral:oas3
```

Is the same as:

```yaml
extends: [[spectral:oas3, recommended]]
```

As far as extending w all, recommended, or none, it should bubble up the hierarchy (I thought that this was happening now, but maybe not?):

E.g. this:

```yaml
extends: [[foo.json, all]]
```

Is the same as:

```yaml
extends: [[bar.json, all], [baz.json, all]]
```

### Todo

- [x] change recommended to be true by default
- [ ] make sure all rules maintain their recommended status (no accidental changes)
- [ ] audit documentation to make sure there is no statements which disagree (for JS, CLI, rulesets in general, custom functions, etc)

**Comment by P0lip** [comment]
@miller79 
Hello!
The reason `model-description` rule is not enabled is caused by the fact it's not a recommended rule, therefore, when you extend the built-in ruleset it's not enabled by default.

In order to have that rule enabled you can do the following:
```yaml
extends: spectral:oas3
rules:
  operation-operationId: error
  model-description: true # you can also set a custom severity error if you'd like to
```

or, alternatively, if you'd like to enable all rules
```
```yaml
extends: [[spectral:oas3, all]]
```
Hope this helps, sorry for any confusion caused.

We are in the process of making CLI default usage of rulesets more consistent.

I added a test here to make sure we never regress https://github.com/stoplightio/spectral/pull/448

**Comment by miller79** [comment]
Thanks I have read this document but did not see the line talking about recommended rules.  My two cents would be that I think it would be easier to read if that recommended rule is stated in the extending rules section and not the disable rules section.  After some trial, I believe I am able to continue and this can be closed unless you would like to capture my comments.

**Comment by P0lip** [comment]
@philsturgeon thoughts on above?
I think that Anthony is in fact right about that and there is a place for improvement in terms of built-in ruleset extension.

**Comment by philsturgeon** [comment]
@P0lip yeah I think our stuff around recommended is incomplete. 

1. Does the CLI by default run all or only recommended 
2. Does ruleset extension by default include all or only recommended 

If those two things are different, then we’ll need to be veeeery clear in the docs about what can be expected. I think this is the current case.

**Comment by miller79** [comment]
From the test I did and after turning all on, it seems that it runs all for the current ruleset and recommended for the extended ruleset.

So focusing on the oas3 ruleset and an extended oas3 ruleset it would look like this

* oas3 only `all`, oas `recommended`
* new ruleset extended default `all`, oas3 `recommended`, oas `recommended`
* new ruleset extended all `all`, oas3 `all`, oas `all`

With that you can never get to how oas3 runs by default without enabling rules manually (or maybe tricking it by setting oas to recommended which I have not tried.

**Comment by marbemac** [comment]
My two cents... recommended should be the default across the board - cli and ruleset extension. 

E.g. this:

```yaml
extends: spectral:oas3
```

Is the same as:

```yaml
extends: [[spectral:oas3, recommended]]
```

As far as extending w all, recommended, or none, it should bubble up the hierarchy (I thought that this was happening now, but maybe not?):

E.g. this:

```yaml
extends: [[spectral:oas3, all]]
```

Is the same as:

```yaml
extends: [[spectral:oas3, all], [spectral:oas, all]]
```

**Comment by philsturgeon** [comment]
This seems like the way to go for sure. This story can be about making sure that is happening.

**Comment by marbemac** [comment]
And perhaps a look at the docs to make sure this behavior is described clearly? @philsturgeon maybe you can take this issue and make it about verification that this is happening + docs audit?

**Comment by philsturgeon** [comment]
Updated the issue to make it clearer what needs to be done. Let's do this for v5.0.

**Comment by P0lip** [comment]
@philsturgeon @marbemac 
I don't understand this part
```yaml
extends: [[spectral:oas3, all]]
```

Is the same as:
```yaml
extends: [[spectral:oas3, all], [spectral:oas, all]]
```

I believe this works as expected.
In any case, we are removing spectral:oas2 and spectral:oas3, so this should not be an issue.

**Comment by marbemac** [comment]
> I don't understand this part

It's just to show an example that the chosen grouping (none, recommended, all, etc) should be applied to every ruleset in the extension hierarchy. For example:

**ruleset_a**

```yaml
rules: {}
```

**ruleset_b**

```yaml
extends: ruleset_a
```

**ruleset_c**

```yaml
extends: [[ ruleset_b, off ]]
```

**my_ruleset**

```yaml
extends: [[ ruleset_c, all ]]
```

The `my_ruleset` above is equivalent of doing:

```yaml
extends: [[ ruleset_c, all ], [ ruleset_b, all ], [ ruleset_a, all ]]
```

---

That's the thought at least - is that how it's working now?

**Comment by P0lip** [comment]
@marbemac @philsturgeon 
Alright, I see now. Thank you for the explanation. Will certainly take a look at it and fix/adjust as needed.

**Comment by mkistler** [comment]
@philsturgeon My recollection is just that the documentation on writing custom functions:

https://stoplight.io/p/docs/gh/stoplightio/spectral/docs/guides/custom-functions.md

does not mention adding `recommended: true` to the custom rule to make it active.  So regardless of what the default is, I think the doc for writing custom functions should at least mention that this property can be specified for a custom function.

**Comment by philsturgeon** [comment]
@mkistler we fixed that the day after the workshop, the docs only go up on a new release. Beyond that quick fix, we are improving Spectral on the whole.
