### ISSUE TITLE
Migrate typeEnum function from a built-in into an oas custom function

### ISSUE THREAD

**Issue by nulltoken** [stoplightio/spectral#924]
**Chore summary**
While working on #913, I tried to implement `typedEnum` as a custotom function. I eventually forfeited.

Having a custom functions with dependencies on external packages such as ajv and built-ins like `assert` and `os`doesn't seem to work out of the box with the current rollup configuration.

**Tasks**
- [ ] Migrate `typedEnum` as a custom oas function
- [ ] Build a very rich custom function, with plenty of dependencies and ensure rollup and karma can digest it without further tweaking
- [ ] Ensure the custom function creation documentation is in line with the required steps to make that work for the end user.
